START = 0
NEUTRAL = 1
GLOBE = 2
GLOBE_SAFE = 3
STAR = 4
GOAL = 5

poses = [GLOBE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,STAR,NEUTRAL,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,STAR,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,STAR,NEUTRAL,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,STAR,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,STAR,NEUTRAL,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,STAR,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,STAR,NEUTRAL,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,STAR,NEUTRAL]
poses = [GLOBE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,STAR,NEUTRAL,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,STAR,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,STAR,NEUTRAL,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,STAR,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,STAR,NEUTRAL,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,STAR,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,NEUTRAL,NEUTRAL,STAR,NEUTRAL,NEUTRAL,GLOBE,NEUTRAL,NEUTRAL,STAR,GOAL_REA,GOAL_REA,GOAL_REA,GOAL_REA,GOAL_REA]

for i,p in enumerate(poses):
    print(i,p)



